### ISSUE TITLE
C interface

### ISSUE THREAD

**Issue by petr-stety-stetka** [ChangSpivey/netinfo#2]
Hello,
Can you please create C interface for netinfo?
In order to use the library from other languages.

It would be great!

**Comment by kaegi** [comment]
I'm currently (meaning this very second) working on it.

It's about 60% finished and will be released soon.

**Comment by kaegi** [comment]
[netinfo-ffi](https://github.com/ChangSpivey/netinfo-ffi) is done now!

**Comment by petr-stety-stetka** [comment]
Thx guy!
